apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-deployment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.port }}
